export const DEFAULT_HOMEPAGE = {
  heroBrandTitle: 'DARK|DIVINE',
  heroScriptSuffix: 'the darkness within',
  heroPrimaryTextDrop: 'Enter the Private Drop',
  heroPrimaryHrefDrop: '/drop',
  heroPrimaryTextShop: 'Shop the Collection',
  heroPrimaryHrefShop: '/shop',
  heroSecondaryText: 'Shop All',
  heroSecondaryHref: '/shop',
  heroMetaItems: [
    { text: 'One run per colorway' },
    { text: 'Free US shipping over ${freeShipThreshold}' },
    { text: 'Secure checkout' },
  ],
  tickerText: 'City of Sins · Drop 002 · One Run. No Restock. · Dark Divine · 00 ·',
  manifestoText: "Every piece is cut once. Sold once. Gone forever. You were either in the run — or you weren't.",
  dropActLabel: 'Act I — Drop 002',
  dropTitle: 'City of|Sins',
  dropBodyLimited: 'Three matched bundles. Jersey plus nylon pants, numbered — no size combo has more than three units. Scroll →',
  dropBodyGeneral: 'Three matched bundles. Jersey plus nylon pants, numbered, cut in small runs. Scroll →',
  dropAnchorText: 'Pieces separately {comparePrice} — the bundle {price}',
  dropProductButtonText: 'View the bundle',
  dropOutroTitle: 'No|Restock',
  dropOutroButtonDrop: 'Enter the Drop',
  dropOutroHrefDrop: '/drop',
  dropOutroButtonShop: 'Shop All',
  dropOutroHrefShop: '/shop',
  dropOutroLogoPoster: '/media/brand/logo-3d.png',
  dropOutroLogoModel: '/media/brand/logo.glb',
  dropOutroLogoAlt: 'Dark Divine serpent crown logo in 3D',
  bestIndex: '02',
  bestEyebrow: 'Most Wanted',
  bestTitle: 'Best Sellers',
  bestButtonText: 'Shop all',
  bestButtonHref: '/shop',
  newIndex: '03',
  newEyebrow: 'Just Landed',
  newTitle: 'New Arrivals',
  storyIndex: '04',
  storyEyebrow: 'The Brand',
  storyScript: 'Illuminate the darkness within',
  storyParagraph1: 'Dark Divine didn’t start in a boardroom. It started with a serpent, a number, and the idea that what you wear should say something before you do.',
  storyParagraph2: 'Every piece runs through the same hands: designed in-house, sampled until the fit is right, and produced in one small run. No warehouse of leftovers. No re-releases. The 00 on the chest isn’t a size — it’s a marker that you were there for the run.',
  storyParagraph3: 'We’d rather sell out than mass-produce. That’s the whole model.',
  storySignature: 'Dark Divine — darkdivine.store',
  storyImage: '/media/editorial/tee-model-pose-2.webp',
  storyImageAlt: 'Dark Divine serpent tee — studio portrait',
  qualityIndex: '05',
  qualityEyebrow: 'Built, Not Printed',
  qualityTitle: "What You're Paying For",
  qualityItems: [
    { number: 'I', title: 'Game-Grade Mesh', text: 'Jerseys are cut from breathable athletic mesh with stitched varsity trim — built like game wear, not novelty prints.' },
    { number: 'II', title: 'Heavyweight Cotton', text: 'Hoodies and sweats are 100% premium cotton fleece that holds structure and survives the dryer.' },
    { number: 'III', title: 'Ripstop Nylon', text: "Track pants in lightweight mesh-lined ripstop — moves fast, doesn't wrinkle, doesn't quit." },
    { number: 'IV', title: 'One Run Only', text: "Small-batch production, numbered drops. Scarcity here isn't marketing — it's how we make things." },
  ],
  socialIndex: '06',
  socialEyebrow: 'Social Proof',
  socialTitle: 'Worn & Vouched',
  socialReviewLabel: 'verified customer reviews\nacross the catalog',
  socialNote: 'Real reviews from verified orders. New ones are collected after checkout — order email required for the Verified badge.',
  reelIndex: '■',
  reelEyebrow: 'The Reel',
  reelTitle: 'Dark Divine|In Motion',
  reelHint: 'drag →',
  reelItems: [
    { type: 'video', src: '/media/editorial/ad1-web.mp4', poster: '/media/editorial/poster-ad1.jpg', tag: 'enter the darkness — the spot', ratio: '16 / 9' },
    { type: 'video', src: '/media/editorial/LTX_2.0_i2v_00019_-web.mp4', poster: '/media/editorial/poster-LTX_2.0_i2v_00019_.jpg', tag: 'the serpent tee', ratio: '1280 / 704' },
    { type: 'image', src: '/media/editorial/ig-hatstore.webp', poster: '', tag: '@darkdivine.official', ratio: '1205 / 1597' },
    { type: 'video', src: '/media/editorial/ComfyUI_00018_-web.mp4', poster: '/media/editorial/poster-ComfyUI_00018_.jpg', tag: 'matching sets', ratio: '1 / 1' },
    { type: 'image', src: '/media/editorial/ig-jersey-fit.webp', poster: '', tag: 'city of sins jersey', ratio: '560 / 790' },
    { type: 'video', src: '/media/editorial/dji-wall.mp4', poster: '/media/editorial/poster-dji-wall.jpg', tag: 'the wall — on set', ratio: '16 / 9' },
    { type: 'video', src: '/media/editorial/LTX_2.0_i2v_00065_-web.mp4', poster: '/media/editorial/poster-LTX_2.0_i2v_00065_.jpg', tag: 'worn, not staged', ratio: '1280 / 704' },
    { type: 'video', src: '/media/editorial/Wan22_00018-web.mp4', poster: '/media/editorial/poster-Wan22_00018.jpg', tag: 'illuminate within', ratio: '480 / 832' },
    { type: 'video', src: '/media/editorial/dji-location.mp4', poster: '/media/editorial/poster-dji.jpg', tag: 'on location — the bridge', ratio: '16 / 9' },
  ],
  lookbookIndex: '07',
  lookbookEyebrow: 'On Instagram',
  lookbookTitle: 'The Lookbook',
  lookbookButtonText: '{instagramHandle}',
  lookbookButtonHref: '{instagram}',
  lookbookItems: [
    { src: '/media/editorial/studio-00-pants.webp', alt: 'Dark Divine 00 nylon pants — studio', tag: 'the 00 pants', to: '/product/city-of-sins-nylon-pants' },
    { src: '/media/editorial/ig-hatstore.webp', alt: 'Dark Divine 00 pants styled in a hat store', tag: '@darkdivine.official', to: '/product/dark-divine-sweat-pants' },
    { src: '/media/editorial/pendant-graded-1.webp', alt: 'Dark Divine serpent pendant and tee — editorial', tag: 'the serpent', to: '/product/dark-divine-t-shirt' },
    { src: '/media/editorial/tee-model-pose.webp', alt: 'Dark Divine serpent tee — studio pose', tag: 'the tee, worn', to: '/product/dark-divine-t-shirt' },
    { src: '/media/editorial/edited-igreel_00018_.webp', alt: 'Dark Divine tee mirror selfie', tag: 'the tee', to: '/product/dark-divine-t-shirt' },
    { src: '/media/editorial/mask-backscript.webp', alt: 'Illuminate The Darkness Within — back script', tag: 'the darkness within', to: '/product/dark-divine-hoodie' },
    { src: '/media/editorial/hoodie-mirror.webp', alt: 'Dark Divine zip hoodie mirror fit', tag: 'the zip hoodie', to: '/product/dark-divine-hoodie' },
    { src: '/media/editorial/ig-jersey-fit.webp', alt: 'City of Sins jersey fit check', tag: 'the jersey', to: '/product/city-of-sins-jersey' },
  ],
  faqIndex: '08',
  faqEyebrow: 'Questions',
  faqTitle: 'Before You Ask',
  faqItems: [
    { question: 'How does sizing run?', answer: 'Jerseys and tees run true to size with a relaxed athletic cut — size up if you want it oversized. Nylon pants are a relaxed straight leg; size down for a tapered stack. Every product page has fit notes and model sizing, and the full [size guide](/size-guide) has flat measurements.' },
    { question: 'When will my order ship?', answer: "Orders ship within {processingDays} business days from the US. Standard delivery is 3–7 business days, and you'll get a tracking number by email the moment it leaves. Full details in the [shipping policy](/shipping)." },
    { question: "What's the return policy?", answer: '{returnsDays} days, unworn with tags, full refund to your original payment — no restocking fee, no interrogation. Drop items are final sale only when marked on the product page. Details in [returns & refunds](/refunds).' },
    { question: 'Will sold-out pieces restock?', answer: 'No. One production run per colorway is the rule the brand is built on. If a size sells out before the run does, join the back-in-stock list on the product page — remaining units sometimes free up from unpaid orders.' },
    { question: 'Is checkout secure?', answer: 'Yes — payments run through Stripe over an encrypted connection, and we never see or store your card number. Accepted: {payMethods}.' },
    { question: 'How do I get a drop access code?', answer: "Join the email list below. Access codes go out to the list before every drop — that's the only place they're published." },
  ],
  signupEyebrow: 'Private List',
  signupTitle: 'First Access or No Access',
  signupBody: 'Drop dates, private access codes, and 10% off your first order. One email per drop — nothing else.',
  signupSuccessText: "You're in. Code {welcomeCode} = 10% off your first order.",
  signupEmailPlaceholder: 'Email address',
  signupButtonText: 'Join the List',
  signupPhonePlaceholder: 'Phone (optional — SMS drop alerts)',
  signupSmsConsent: 'I agree to receive automated SMS drop alerts from Dark Divine. Msg & data rates may apply. Reply STOP to opt out.',
  signupNote: 'Unsubscribe anytime. We never sell your info.',
  signupVideo: '/media/brand/logo-3d-web.mp4',
  signupVideoPoster: '',
};

export function mergeHomepage(overrides = {}) {
  return {
    ...DEFAULT_HOMEPAGE,
    ...(overrides && typeof overrides === 'object' && !Array.isArray(overrides) ? overrides : {}),
  };
}

export function formatHomepageText(value, context = {}) {
  return String(value ?? '').replace(/\{([A-Za-z0-9_]+)\}/g, (token, key) => (
    Object.prototype.hasOwnProperty.call(context, key) ? String(context[key] ?? '') : token
  ));
}
