// Supabase Edge Function: order-status
// Token-protected order lookup for the customer status page.
//
// Security model: every order gets an unguessable access_token (24 random
// bytes, generated by the database). The status link mailed to the customer
// is /order-status?o=<order-id>&t=<token>; this function releases order
// data ONLY when both match. Order ids alone reveal nothing, there is no
// email-only lookup (emails are guessable), and the anon key has no SELECT
// policy on orders at all.
//
// Body: { order, token }  → { ok, order } | { ok:false }
// Deploy: supabase functions deploy order-status --use-api
import { createClient } from 'npm:@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const STAGE_LABELS: Record<string, string> = {
  received: 'Preorder received',
  preorder_closed: 'Preorder closed',
  production_scheduled: 'Production scheduled',
  materials_secured: 'Materials secured',
  in_production: 'In production',
  quality_control: 'Quality control',
  preparing_shipment: 'Preparing shipment',
  shipped: 'Shipped',
  delivered: 'Delivered',
  delayed: 'Delayed',
  cancelled: 'Cancelled',
  refunded: 'Refunded',
};

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });

  try {
    const { order, token } = await req.json();
    const id = String(order ?? '').trim();
    const tok = String(token ?? '').trim();
    // both halves required; tokens are 48 hex chars — anything shorter is a probe
    if (!id || tok.length < 20) return json({ ok: false }, 404);

    const supabase = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
    );

    const { data: o } = await supabase.from('orders')
      .select('id, status, production_status, total, tracking, created_at, campaign_id, est_ship_start, est_ship_end, access_token, balance_due, balance_status, shipping')
      .eq('id', id).maybeSingle();
    if (!o || o.access_token !== tok) return json({ ok: false }, 404);

    const [{ data: items }, campaign, update] = await Promise.all([
      supabase.from('order_items').select('title, option1, option2, qty, price').eq('order_id', id),
      o.campaign_id
        ? supabase.from('preorder_campaigns')
            .select('name, slug, status, closes_at, estimated_production_start, estimated_shipping_start, estimated_shipping_end')
            .eq('id', o.campaign_id).maybeSingle().then((r) => r.data)
        : Promise.resolve(null),
      o.campaign_id
        ? supabase.from('preorder_campaign_updates')
            .select('title, body, stage, created_at')
            .eq('campaign_id', o.campaign_id).eq('published', true)
            .order('created_at', { ascending: false }).limit(1)
            .then((r) => r.data?.[0] ?? null)
        : Promise.resolve(null),
    ]);

    return json({
      ok: true,
      order: {
        number: String(o.id).slice(0, 8).toUpperCase(),
        payment_status: o.status,
        production_status: o.production_status,
        production_label: o.production_status ? (STAGE_LABELS[o.production_status] ?? o.production_status) : null,
        total: o.total,
        balance_due: Number(o.balance_due || 0),
        balance_status: o.balance_status || 'none',
        tracking: o.tracking,
        shipping: o.shipping ?? null,
        created_at: o.created_at,
        est_ship_start: o.est_ship_start ?? campaign?.estimated_shipping_start ?? null,
        est_ship_end: o.est_ship_end ?? campaign?.estimated_shipping_end ?? null,
        items: items ?? [],
        campaign: campaign ? { name: campaign.name, slug: campaign.slug, status: campaign.status, closes_at: campaign.closes_at } : null,
        latest_update: update,
      },
    });
  } catch {
    return json({ ok: false }, 400);
  }
});

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  });
}
